name: after-tag
on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows:
      - "publish-tag"
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'yay'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
