name: after-tag
on:
  push:
    tags:
      - "*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'yay'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
