name: after-tag
on:
  workflow_run:
    workflows: ["before-tag"]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: |
          if [[ "$(git log -n 1 --pretty=format:'%H')" == "$(git log -n 1 --pretty=format:'%H' $(git describe --abbrev=0 --tags))" ]]; then
            echo "yay after tag"
          else
            echo "no tag"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
