name: before-tag
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'release tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
