name: before-tag
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: release-tag
        run: git config --local user.name test && git config --local user.email "something@mail.com" && git tag -a "$RANDOM" -m "new tag" && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
